{% set name = "marshmallow-oneofschema" %}
{% set version = "3.2.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marshmallow_oneofschema-{{ version }}.tar.gz
  sha256: c06c8d9f14d51ffff152d66d85bd5f27d55cff10752a3b1f8c1f948bf5f597a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - marshmallow >=3.0.0,<5.0.0

test:
  source_files:
    - tests
  imports:
    - marshmallow_oneofschema
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/marshmallow-code/marshmallow-oneofschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Marshmallow library extension that allows schema (de)multiplexing
  description: |
    This library adds a special kind of schema that actually multiplexes other schemas based on object type. 
    When serializing values, it uses get_obj_type() method to get object type name. Then it uses type_schemas 
    name-to-Schema mapping to get schema for that particular object type, serializes object using that schema and
    adds an extra field with name of object type. Deserialization is reverse.
  dev_url: https://github.com/marshmallow-code/marshmallow-oneofschema
  doc_url: https://marshmallow.readthedocs.io
extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
