{% set name = "marshmallow-oneofschema" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62cd2099b29188c92493c2940ee79d1bf2f2619a71721664e5a98ec2faa58237

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - marshmallow >=3.0.0,<4.0.0

test:
  imports:
    - marshmallow_oneofschema

about:
  home: https://github.com/marshmallow-code/marshmallow-oneofschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Marshmallow library extension that allows schema (de)multiplexing

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
