travis:
  secure:
    BINSTAR_TOKEN: IMyy8I+HN33Mdfw6HlJvQOcIwk/EF4W1qZ3hIMNUjylyd8kfClEThz/o5ZooTai7Dhvz0Gl21juBn/foiAooJCrLAga5kL2yUmrgldPsseIyAV3ZQYAEUJ3QZjjks10xnwsNfoPEp1szpaKAAD6T6yItSnHMvsoxDyQHHavoiOcYyjYo4Ms1oOMt+dOd2l9rjobmrVaDCoGIibMyIGL7fHd23P9PZTqS97ENbch7xivxCor4JK2C9asdQSjVk2GK5a6WHt4E7pMEH9qqTj162CRhX6fDx75yzMXji8swP6Eu0bzjfYcobMbFyvDRxRSF3u46zJahoSr/Jrb1LosS2ifQiVXr1UD8M38t9Cn5XjGAZs820wfBzvyTXo+awiU59LfKLpRAG/7ViM9llTaQjwwPetQJfEKF2NxiDwMEhroz7yh5qkiTPJcmj5nFo5XxgATBZvK84HaTkC2KokD/TVSne5DZUvAGaajaaohmHtNdyxMWip3bpuxamgtHFaQcyXBOEc1d8r+eoLcWoNy2ioN6XdqmM+PAxR7OUsRvsctKqje44lQhU9eYTrDqOOpJQRHO2ha56bBwsv8K2sxYbz28CIfOgx8pXT1TwK+obIRKvoNk06YV/R49zoYB5l6Lthpn3dEgulxP8l2ai8eUTeAeCk7HoRaQ5MUpHZpd+G0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
